version: "3.6"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 127.0.0.1:27017:27017

  app:
    depends_on:
      - mongodb
    image: graphqlmovies:latest
    ports:
      - 127.0.0.1:5000:5000
    environment:
      MONGO_HOST: mongodb

